### ISSUE TITLE
Make output dir more configurable

### ISSUE THREAD

**Issue by ashleyvega** [protobuffet/docusaurus-protobuffet#1]
Hi @AnthonyBobsin. Thanks for this plugin, it's very useful.

However, I'd like docs to appear in a directory other than `protodocs`, but I see it's hardcoded in a couple of places:

https://github.com/protobuffet/docusaurus-protobuffet/blob/ccf760c0d03114a69a713940b90b89342e69e5c7/packages/docusaurus-protobuffet/src/index.ts#L43-L44

https://github.com/protobuffet/docusaurus-protobuffet/blob/ccf760c0d03114a69a713940b90b89342e69e5c7/packages/docusaurus-protobuffet-plugin/src/parsers.ts#L16-L17

**Comment by ashleyvega** [comment]
@AnthonyBobsin I'll fork the repo and see if I can get a PR going.

**Comment by AnthonyBobsin** [comment]
Hey @ashleyvega, I'm glad the plugin has been useful for you!

Storing docs in a different directory is a reasonable request and something I've intended to support.

Feel free to give it a shot and reach out if you need any guidance :) I've got some time available over the next week, so I can support or implement as needed.

**Comment by AnthonyBobsin** [comment]
I've added support to configure the `routeBasePath` option and fixed the specified `path` option in PR #2. You can access this new functionality in the published version 0.3.0 and see the configuration available on our doc site: https://protobuffet.com/docs/how/usage/#configuration.

The PR explains the changes in detail, but the high-level idea is that I've introduced the following changes:
- You can now specify the `docs.routeBasePath` option to modify the base route.
- `protobuffet.protoDocsPath` is now used for the `@docusaurus/plugin-content-docs` plugin's `path` option as well.

I'm closing this issue since this should have solved the problem faced of the hard-coded `protodocs`, but feel free to re-open if there is some missing functionality or concerns with the implementation. Thanks!
